spring:
  application:
    name: algotrading
  datasource:
    url: jdbc:postgresql://localhost:8001/algotrading
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

finnhub:
  base-url: ${FINNHUB_BASE_URL}
  api-key: ${FINNHUB_API_KEY}

ntfy:
  topic-name: ${NTFY_TOPIC_NAME}
  base-url: ${NTFY_BASE_URL}

saxo-sim-api:
  base-url: ${SAXO_SIM_BASE_URL}
  api-token: ${SAXO_24H_TOKEN}