spring:
  application:
    name: algotrading
  datasource:
    url: jdbc:postgresql://localhost:8001/algotrading
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

finnhub:
  base-url: ${FINNHUB_BASE_URL}
  api-key: ${FINNHUB_API_KEY}

ntfy:
  topic-name: ${NTFY_TOPIC_NAME}
  base-url: ${NTFY_BASE_URL}

saxo-sim-api:
  base-url: https://gateway.saxobank.com/sim/openapi
  streaming-url: wss://sim-streaming.saxobank.com/sim/oapi/streaming/ws
  oauth:
    app-key: ${SAXO_APP_KEY}
    app-secret: ${SAXO_APP_SECRET}
    redirect-url: http://localhost:8080/api/saxo/oauth/callback
    authorization-url: https://sim.logonvalidation.net/authorize
    token-url: https://sim.logonvalidation.net/token