spring:
  application:
    name: algotrading
  datasource:
    url: jdbc:postgresql://localhost:8001/algotrading
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

finnhub:
  base-url: ${FINNHUB_BASE_URL}
  api-key: ${FINNHUB_API_KEY}

ntfy:
  stock-topic-name: ${NTFY_STOCK_TOPIC_NAME}